### ISSUE TITLE
Can't generate parsed file for mc500.train

### ISSUE THREAD

**Issue by nicola** [elleryjsmith/UCLMCTest#15]
``` bash
$ jython -Dpython.path=stanford-parser.jar:stanford-parser-3.5.0-models.jar:/Library/Python/2.7/site-packages parsecache.py mc500.train
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.3 sec].
Parsing sentence: " Alyssa got to the beach after a long trip."
Traceback (most recent call last):
  File "parsecache.py", line 38, in <module>
    pickle.dump([story.parserepr() for story in stories],fl)
  File "parsecache.py", line 20, in storyparser
    yield JStory.fromdata(rw,parser)
  File "/Users/mozilla/Proj/nlp/UCLMCTest/stanfordclasses.py", line 32, in fromdata
    stry.sentences = stry._extractsentences(txt)
  File "/Users/mozilla/Proj/nlp/UCLMCTest/stanfordclasses.py", line 58, in _extractsentences
    s.parse = s._parse()
  File "/Users/mozilla/Proj/nlp/UCLMCTest/stanfordclasses.py", line 89, in _parse
    return self.parser.apply(self)
  File "/Users/mozilla/Proj/nlp/UCLMCTest/stanfordclasses.py", line 155, in apply
    return JSentenceParse.fromtree(self,self.parser.apply(sentence.tokens))
  File "/Users/mozilla/Proj/nlp/UCLMCTest/stanfordclasses.py", line 180, in fromtree
    for i,t in enumerate(tkn,1):
TypeError: enumerate() takes at most 1 arguments (2 given)
```

**Comment by nicola** [comment]
my mistake, it uses jython 2.7
