### ISSUE TITLE
Attached code is not working

### ISSUE THREAD

**Issue by chander-livai** [elleryjsmith/UCLMCTest#77]
Getting the following error on running the clean download of the code as per README
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    results.printresults()
  File "/home/chander/UCLMCTest/results.py", line 9, in printresults
    for d in ["dev","train","devtrain","test"]}
  File "/home/chander/UCLMCTest/results.py", line 9, in <dictcomp>
    for d in ["dev","train","devtrain","test"]}
  File "/home/chander/UCLMCTest/scoring.py", line 274, in scoredataset
    return {"rte":scorewithflags(split,flags,rte=True,grade=grade),
  File "/home/chander/UCLMCTest/scoring.py", line 244, in scorewithflags
    for l,f in flags.items()}
  File "/home/chander/UCLMCTest/scoring.py", line 244, in <dictcomp>
    for l,f in flags.items()}
  File "/home/chander/UCLMCTest/scoring.py", line 243, in <dictcomp>
    for n,s in datasets[devtest].items()}
  File "/home/chander/UCLMCTest/scoring.py", line 226, in scoreset
    scores = score(stories,scoref,**flags[scoref])
  File "/home/chander/UCLMCTest/scoring.py", line 72, in score
    word,negation,hypernymy,categorise),s)
  File "/home/chander/UCLMCTest/scoring.py", line 88, in scoretoks
    if categorise and all([categories[c] for c in story["categories"][i]]):
KeyError: u'temporal'

**Comment by andreasvlachos** [comment]
Greetings,

Apologies for this. Not exactly a solution, but if you checkout the penultimate version using:

git checkout 97c7c86ea0e153025e667255adb799e43b25c8b5

it works OK.

Thanks,
Andreas

**Comment by elleryjsmith** [comment]
Sorry about that
Hopefully fixed in latest
